/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Patient;
import java.awt.Color;
import javax.swing.BorderFactory;
//import Business.VitalSignHistory;
//import Business.VitalSign;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author priyank
 */
public class CreatePatientJPanel extends javax.swing.JPanel   {

    /**
     * Creates new form CreatePatientJPanel
     */
   private Patient patient;
    public CreatePatientJPanel( Patient P ) {
        initComponents();
        this.patient = P;
        Border B = BorderFactory.createLineBorder(Color.BLUE, 1);
        txtPatientName.setBorder(B);
        txtPatientID.setBorder(B);
         txtAge.setBorder(B);
         txtPrimaryDoctorName.setBorder(B);
         txtPrefferedPharmacy.setBorder(B);
    }
    
//public Exception EmptyTextFieldException (String message){
//     JOptionPane.showMessageDialog(null,"Filed is Blank", ui, message, WIDTH);message;
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPrimaryDoctorName = new javax.swing.JTextField();
        txtPrefferedPharmacy = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Patient ID");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("Age");

        jLabel4.setText("Primary Doctor Name");

        jLabel5.setText("Preffered Pharmacy");

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Patient Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientID)
                            .addComponent(txtAge)
                            .addComponent(txtPrimaryDoctorName)
                            .addComponent(txtPrefferedPharmacy)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPatientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatientID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrimaryDoctorName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrefferedPharmacy))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(79, 79, 79)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       Border R = BorderFactory.createLineBorder(Color.RED, 5);
       Border B = BorderFactory.createLineBorder(Color.BLUE, 1);
         String PN =toUpperCase(txtPatientName.getText().trim());
         String PI = toUpperCase(txtPatientID.getText().trim());
         String Age = txtAge.getText().trim();
         String PD = toUpperCase(txtPrimaryDoctorName.getText().trim());
         String PP = toUpperCase(txtPrefferedPharmacy.getText().trim());
         try {
             int i ;
             i = (PN.length()* PI.length()* Age.length()* PD.length()*PP.length());
             if ( i==0)
             {
                
             
                 throw new Exception(" Fields can Not be Empty. ");
             
             }
       patient.setPatientName(PN);
       patient.setPatientID(PI);
       patient.setAge(Integer.parseInt(Age));
       patient.setPrimaryDoctorName(PD);
       patient.setPreferredPharmacy(PP);
       
        txtPatientName.setEnabled(false);
        txtPatientID.setEnabled(false);
        txtAge.setEnabled(false);
        txtPrimaryDoctorName.setEnabled(false);
        txtPrefferedPharmacy.setEnabled(false);
        txtPatientName.setBorder(B);
        txtPatientID.setBorder(B);
         txtAge.setBorder(B);
         txtPrimaryDoctorName.setBorder(B);
         txtPrefferedPharmacy.setBorder(B);
         JOptionPane.showMessageDialog(null," Patient Details saved successfully");
    }
         catch (Exception e)
         {
             if (e.toString().contains("NumberFormat"))
             {
                 JOptionPane.showMessageDialog(null, "Age format is not correct.","Information Message",JOptionPane.INFORMATION_MESSAGE);
                         txtPatientName.setBorder(B);
        txtPatientID.setBorder(B);
         txtAge.setBorder(R);
         txtPrimaryDoctorName.setBorder(B);
         txtPrefferedPharmacy.setBorder(B);
             }
             else
             {
         JOptionPane.showMessageDialog(null, e,"Information Message",JOptionPane.INFORMATION_MESSAGE);
         }
         }
         finally
                 {
                      if (PN.length() == 0)
                txtPatientName.setBorder(R);
                 else 
                 txtPatientName.setBorder(B);
                   if (PN.length() == 0)
                 txtPatientID.setBorder(R);
               else
               txtPatientID.setBorder(B);
                    if (Age.length() == 0)
             
                 txtAge.setBorder(R);
              // else
                 //       txtAge.setBorder(B);
             
                     if (PD.length() == 0)
             
                 txtPrimaryDoctorName.setBorder(R);
               else
                         txtPrimaryDoctorName.setBorder(B);
             
                      if (PP.length() == 0)
             
                 txtPrefferedPharmacy.setBorder(R);
               else
                          txtPrefferedPharmacy.setBorder(B);
                 
                 }
             
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPrefferedPharmacy;
    private javax.swing.JTextField txtPrimaryDoctorName;
    // End of variables declaration//GEN-END:variables
}
