/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import javax.swing.JOptionPane;
import Business.Product;
import java.awt.Color;
/**
 *
 * @author priyank
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Product product;
    public CreateJPanel( ) {
        initComponents();
    }
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarMake = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        lblCarModel = new javax.swing.JLabel();
        txtCarMake = new javax.swing.JTextField();
        lblMiles = new javax.swing.JLabel();
        txtCarModel = new javax.swing.JTextField();
        lblBatteryStatus = new javax.swing.JLabel();
        txtMiles = new javax.swing.JTextField();
        lblEngineStatus = new javax.swing.JLabel();
        txtBatteryStatus = new javax.swing.JTextField();
        lblOilStatus = new javax.swing.JLabel();
        txtEngineStatus = new javax.swing.JTextField();
        lblServiceDate = new javax.swing.JLabel();
        txtServiceDate = new javax.swing.JTextField();
        lblServiceDescription = new javax.swing.JLabel();
        txtServiceDescription = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerPhoneNumber = new javax.swing.JTextField();
        lblCustomerPhoneNumber = new javax.swing.JLabel();
        txtOilStatus = new javax.swing.JTextField();
        btnLog = new javax.swing.JButton();

        lblCarMake.setText("Car Make");

        lblEmailAddress.setText("Email Address");

        lblCarModel.setText("Car Model");

        lblMiles.setText("Miles");

        lblBatteryStatus.setText("Battery Status");

        txtMiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMilesActionPerformed(evt);
            }
        });

        lblEngineStatus.setText("Engine Status");

        txtBatteryStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatteryStatusActionPerformed(evt);
            }
        });

        lblOilStatus.setText("Oil Status");

        lblServiceDate.setText("Service Date");

        lblServiceDescription.setText("Service Description");

        lblCustomerName.setText("Customer Name");

        lblCustomerPhoneNumber.setText("Customer Phone Number");

        btnLog.setText("Log Data");
        btnLog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCustomerPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServiceDescription, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServiceDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOilStatus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEngineStatus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBatteryStatus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMiles, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarModel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarMake, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCarModel)
                    .addComponent(txtMiles)
                    .addComponent(txtBatteryStatus)
                    .addComponent(txtEngineStatus)
                    .addComponent(txtOilStatus)
                    .addComponent(txtServiceDate)
                    .addComponent(txtServiceDescription)
                    .addComponent(txtCarMake))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarMake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMiles))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBatteryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBatteryStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEngineStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEngineStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOilStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        txtCarMake.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtMilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMilesActionPerformed

    private void txtBatteryStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatteryStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatteryStatusActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        int i;
        product.trimText(txtCarMake.getText(),txtCarModel.getText(),txtMiles.getText(),txtBatteryStatus.getText(),txtEngineStatus.getText(),txtOilStatus.getText(),txtServiceDate.getText(),txtServiceDescription.getText(),txtCustomerName.getText(),txtCustomerPhoneNumber.getText(),txtEmailAddress.getText());
            i =  (txtCarMake.getText().length()*txtCarModel.getText().length() * txtMiles.getText().length()
                    * txtBatteryStatus.getText().length() * txtEngineStatus.getText().length() 
                    * txtOilStatus.getText().length()  *txtServiceDate.getText().length() 
                    * txtServiceDescription.getText().length() * txtCustomerName.getText().length()
                    * txtCustomerPhoneNumber.getText().length() * txtEmailAddress.getText().length());
                if (i== 0 )
                    
                {
                   String errMessage= " Any of the field can not be left blank.";
                   String mainBar = "ERROR";
                   JOptionPane.showMessageDialog(null, errMessage, "Information: " + mainBar, JOptionPane.INFORMATION_MESSAGE);
                   
                   if(txtCarMake.getText().length() == 0)
                   lblCarMake.setForeground(Color.red);
                   else
                     lblCarMake.setForeground(Color.black);  
                   if(txtCarModel.getText().length() == 0)
                     lblCarModel.setForeground(Color.red); 
                   else
                      lblCarModel.setForeground(Color.black); 
                   if(txtMiles.getText().length() == 0)
                     lblMiles.setForeground(Color.red); 
                   else
                      lblMiles.setForeground(Color.black);  
                   if(txtBatteryStatus.getText().length() == 0)
                     lblBatteryStatus.setForeground(Color.red); 
                   else
                       lblBatteryStatus.setForeground(Color.black); 
                   if(txtEngineStatus.getText().length() == 0)
                     lblEngineStatus.setForeground(Color.red); 
                   else
                   lblEngineStatus.setForeground(Color.black); 
                   if(txtOilStatus.getText().length() == 0)
                     lblOilStatus.setForeground(Color.red); 
                   else
                      lblOilStatus.setForeground(Color.black);   
                   if(txtServiceDate.getText().length() == 0)
                     lblServiceDate.setForeground(Color.red); 
                   else
                       lblServiceDate.setForeground(Color.black); 
                   if(txtServiceDescription.getText().length() == 0)
                     lblServiceDescription.setForeground(Color.red); 
                   else
                       lblServiceDescription.setForeground(Color.black); 
                   if(txtCustomerName.getText().length() == 0)
                     lblCustomerName.setForeground(Color.red); 
                   else
                       lblCustomerName.setForeground(Color.black); 
                   if(txtCustomerPhoneNumber.getText().length() == 0)
                     lblCustomerPhoneNumber.setForeground(Color.red); 
                   else
                       lblCustomerPhoneNumber.setForeground(Color.black); 
                   if(txtEmailAddress.getText().length() == 0)
                     lblEmailAddress.setForeground(Color.red); 
                   else
                       lblEmailAddress.setForeground(Color.black);
                }
                else 
                {
                    product.setCarMake(txtCarMake.getText());
         product.setCarModel(txtCarModel.getText());
          product.setMiles(txtMiles.getText());
           product.setBatteryStatus(txtBatteryStatus.getText());
            product.setEngineStatus(txtEngineStatus.getText()); 
            product.setOilStatus(txtOilStatus.getText());
             product.setServiceDate(txtServiceDate.getText());
              product.setServiceDescription(txtServiceDescription.getText());
               product.setCustomerName(txtCustomerName.getText());
                product.setCustomerPhoneNumber(txtCustomerPhoneNumber.getText()); 
                product.setEmailAddress(txtEmailAddress.getText());
                String successMessage= " Successfully! Logged data. Click View Log to display.";
                   String mainBar = "Message";
                   JOptionPane.showMessageDialog(null, successMessage, "Information : " + mainBar, JOptionPane.INFORMATION_MESSAGE);
                   
                   lblBatteryStatus.setForeground(Color.black);
                   lblCarMake.setForeground(Color.black);
                   lblCarModel.setForeground(Color.black);
                   lblCustomerName.setForeground(Color.black);
                   lblCustomerPhoneNumber.setForeground(Color.black);
                   lblEmailAddress.setForeground(Color.black);
                   lblEngineStatus.setForeground(Color.black);
                   lblMiles.setForeground(Color.black);
                   lblOilStatus.setForeground(Color.black);
                   lblServiceDate.setForeground(Color.black);
                   lblServiceDescription.setForeground(Color.black);
                
                }
            
        
    }//GEN-LAST:event_btnLogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JLabel lblBatteryStatus;
    private javax.swing.JLabel lblCarMake;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerPhoneNumber;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEngineStatus;
    private javax.swing.JLabel lblMiles;
    private javax.swing.JLabel lblOilStatus;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JLabel lblServiceDescription;
    private javax.swing.JTextField txtBatteryStatus;
    private javax.swing.JTextField txtCarMake;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhoneNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEngineStatus;
    private javax.swing.JTextField txtMiles;
    private javax.swing.JTextField txtOilStatus;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtServiceDescription;
    // End of variables declaration//GEN-END:variables
}
